### ISSUE TITLE
PixiJS 5.0.0-alpha.3 

### ISSUE THREAD

**Issue by Shahdee** [knocknote/pixi-after-effects#8]
Hello!
I've tried launching example, using PixiJS v5.0.0-alpha.3, but it doesn't work. 
When will the after effect plugin support this version of pixi? 
<img width="836" alt="mozilla firefox 2019-01-22 23-12-09" src="https://user-images.githubusercontent.com/1128818/51562708-86181480-1e9b-11e9-8e6a-563d4e199cf8.png">

**Comment by goccy** [comment]
Hi !!
Supported v5 by https://github.com/knocknote/pixi-after-effects/pull/14 !
Thanks
